### ISSUE TITLE
Backend: Implement notification channels

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboards#128]
- [ ] Notification channels: GET `/notificationChannels`
- [ ] Notification channels: POST `/notificationChannels`
- [ ] Notification channels: PUT `/notificationChannels/{uuid}`
- [ ] Notification channels: DELETE `/notificationChannels/{uuid}`
