### ISSUE TITLE
Overview: Prevalence over time

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#3]
### Tasks

- [ ] Support logarithmic and logistic scales
- [ ] Add confidence intervals (it should be possible to enable/disable them)
- [ ] Add [bubbles](https://www.chartjs.org/docs/latest/charts/bubble.html) to the line chart
	- The size of the bubbles scales with the absolute number of sequences.
	- The bubbles always use non-smoothed data.
	- It should be possible to enable/disable them.
- [ ] Allow users to sort the table by any of the columns
- [ ] Add basic styling to the table
- [ ] Add absolute number of sequences to the table
- [ ] Add download button to download the (calculated) data as a TSV (same data as shown in the table)
- [ ] Dispatch an event when the user hovers over a date range
- [ ] Write a basic description
