### ISSUE TITLE
Dashboard for all Influenza data without alignment but with subtypes (and lineages)

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboards#377]
- [x] General influenza: create a basic Loculus instance
- [x] General influenza: add subtype
- [ ] #487
- [x] General influenza: write dashboard page

**Comment by anna-parker** [comment]
I have started working on this - it is not so trivial as loculus requires sequences to be labeled with their segment when uploaded to the DB - this information is not included directly in the downloaded sequence data. I have been experimenting with ways to add this here: https://github.com/GenSpectrum/dashboards/blob/add_more_influenza/InfluenzaA_all_subtypes.ipynb

**Comment by anna-parker** [comment]
I have created a loculus instance for all Influenza A with subtypes here: https://virus4.loculus.org/ see details here: https://github.com/loculus-project/private_deployments/pull/7

**Comment by anna-parker** [comment]
closing this, Influenza B can be done in a separate PR: https://github.com/GenSpectrum/dashboards/issues/488 adding lineages is not a priority and can be moved to the backlog: https://github.com/GenSpectrum/dashboards/issues/487
