### ISSUE TITLE
Overview: Relative growth advantage

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#4]
### Tasks

- [ ] Support logarithmic and logistic scales
- [ ] Dispatch an event when the user hovers over a date range
- [ ] Write a basic description
