### ISSUE TITLE
Overview: Mutations

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#5]
## Tasks

- [ ] Grid: Use background colors for different prevalences
- [ ] Table: Allow users to sort by any of the columns
	- Mutations should be sorted by their position (if segmented, they should first be sorted by their segment and then by their position within the segment)
- [ ] Table: Add basic styling
- [ ] Add the mutation over time visualization in a new tab (see CoV-Spectrum)
- [ ] Allow users to set a min proportion
	- Table: Only mutations greater-than-equal the min proportion should be shown
	- Grid: Only rows where at least one mutation is greater-than-equal the min proportion should be shown
- [ ] Add a download button to download the data as a TSV (same data as shown in the table)
- [ ] Write a basic description
