### ISSUE TITLE
Overview: Mutation comparison

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#6]
The mutation comparison component serves the comparison of mutations of multiple variants. To analyze the mutations of a single variant, the mutations component (#5) should be used.

## Tasks

- [ ] Table: Add a table view that, for each mutation, shows the prevalence in the different variants
- [ ] Table: Allow users to sort by any of the columns (similar to #5)
- [ ] Venn diagram: For up to 4 variants, a Venn diagram view should be available (similar to CoV-Spectrum)
- [ ] [UpSet diagram](https://upset.app/): Add a UpSet diagram (or something inspired by it)
  - Each row is a mutation and each column is a variant.
- [ ] Allow users to set a min proportion (similar to #5)
- [ ] Allow users to filter by mutation type (substitution/deletion/insertion)
- [ ] Add a download button to download the data as a TSV (same data as shown in the table),
- [ ] Write a basic description
